# Generated by Django 4.0.4 on 2022-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_seat',
            name='flight_class',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
